### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by mrromarius** [mrromarius/card-i-docs#1]
- [ ] Function Add "organization"

- [ ] Generation form of class "organization"

- [ ] Generation field to BD
